CREATE SEQUENCE IF NOT EXISTS typ_sq MINVALUE 1 START WITH 1;
CREATE TABLE IF NOT EXISTS typ (
    id INTEGER NOT NULL DEFAULT nextval('typ_sq'),
    title VARCHAR(200) NOT NULL,
    CONSTRAINT pk_typ PRIMARY KEY(id)
);