CREATE SEQUENCE IF NOT EXISTS rule_sq MINVALUE 1 START WITH 1;
CREATE TABLE IF NOT EXISTS rule (
     id INTEGER NOT NULL DEFAULT nextval('rule_sq'),
     title VARCHAR(200) NOT NULL,
     CONSTRAINT pk_rule PRIMARY KEY(id)
);